bart_upstream/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  devise_for :users
  resources :bartstations

  resources :bartroutes

  resources :bartroutestations

  resources :bartjourneys
  
  get '/seed_stations' => 'bartstations#seed_bart_stations'

  get '/unseed_stations' => 'bartstations#unseed_bart_stations'

  get '/seed_bart_routes' => 'bartroutes#seed_bart_routes'

  get '/unseed_bart_routes' => 'bartroutes#unseed_bart_routes'

  get '/remove_bart_route_stations' => 'bartroutestations#remove_bart_route_stations'

  get '/sms' => 'bartjourneys#sms'

  get '/testme' => 'bartjourneys#testme'

  root 'bartjourneys#new'

end

bart_upstream/app/models/bartroutestation.rb
class Bartroutestation < ActiveRecord::Base
 
  belongs_to :bartstation
  belongs_to :bartroute

  validates :bartstation_id, :presence => true
  validates :bartroute_id, :presence => true
  validates :route_station_sequence, :presence => true
   
end

bart_upstream/app/controllers/bartroutestations_controller.rb
class BartroutestationsController < ApplicationController

	include BartroutestationsHelper

	def index
		@bartroutestations = Bartroutestation.all.order('bartroute_id', 'route_station_sequence')
	end

	def new
		get_bart_station_pickers
		@bartroutestation = Bartroutestation.new
	end

	# Create a new route station association
	def create
 		@bartroutestation = Bartroutestation.new(bartroutestation_params)
		if @bartroutestation.save
			flash[:success] = "Route station created"
			redirect_to bartroutestations_path 
		else
			flash[:error] = "Unable to save route station. Please try again"
			get_bart_station_pickers
			render :new
		end
	end

	def edit
		get_bart_station_pickers
		@bartroutestation = Bartroutestation.find(params[:id])
	end

	# Update the modified route station and redirect back to the index
	def update
		@bartroutestation = Bartroutestation.find(params[:id])
#		@bartroutestation.route_station_sequence = (params['bartroutestation']['route_station_sequence'])
		if @bartroutestation.update(bartroutestation_params)
			flash[:success] = "Route station updated"
			redirect_to bartroutestations_path
		else
			render :edit
		end
	end

	def remove_bart_route_stations
		remove_all_bart_route_stations
		redirect_to bartroutestations_path
	end

	private

    def bartroutestation_params
      params.require(:bartroutestation).permit(:bartroute_id, :bartstation_id,:route_station_sequence)
    end

end

bart_upstream/app/helpers/bartroutestations_helper.rb
module BartroutestationsHelper

	def get_bart_station_pickers
		@bartroutestation = Bartroutestation.new
		@bartstations = Bartstation.all
		@bartstation_names = {}
		@bartstations.each do |bartstation|
			@bartstation_names[bartstation.station_name] = bartstation.id
		end 
		@bartroutes = Bartroute.all
		@bartroute_names = {}
		@bartroutes.each do |bartroute|
			@bartroute_names[bartroute.bart_route_name] = bartroute.id
		end 
	end

	# Remove all the station information from the database. Used in testing only
	def remove_all_bart_route_stations
		@stations = Bartroutestation.all
		@stations.each do |station|
			station.destroy
		end
	end

end

bart_upstream/app/views/bartroutestations/_editform.html.erb
<div class="col-lg-7 col-lg-offset-2">
<div class="well">

<p class="body_font body_color">
Please choose a route and its associated station:
</p>
<%= simple_form_for(@bartroutestation, 
    html: {:class => 'form-horizontal'}) do |f| %>
    <%= f.input :bartroute_id, collection: @bartroute_names, label: false, 
        input_html:{:class => 'form-control body_font body_color'} %>
    </br>
    <%= f.input :bartstation_id, collection: @bartstation_names,label: false, 
        input_html:{:class => 'form-control body_font body_color'} %>
    </br>
    <%= f.input :route_station_sequence, label: false, 
        input_html:{:class => 'form-control body_font body_color', placeholder: "Station sequence"} %>
    </br>
    <%= f.submit "Submit".html_safe, :class => 'btn btn-lg btn-success body_font body_color' %>
<% end %>

</div>
</div>

bart_upstream/app/views/bartroutestations/_form.html.erb
<div class="col-lg-7 col-lg-offset-2">
<div class="well">

<p class="body_font body_color">
Please choose a route and its associated station:
</p>
<%= simple_form_for(@bartroutestation, 
    html: {:class => 'form-horizontal'}) do |f| %>
    <%= f.input :bartroute_id, collection: @bartroute_names, label: false, 
        input_html:{:class => 'form-control body_font body_color'} %>
    </br>
    <%= f.input :bartstation_id, collection: @bartstation_names,label: false, 
        input_html:{:class => 'form-control body_font body_color'} %>
    </br>
    <%= f.input :route_station_sequence, label: false, 
        input_html:{:class => 'form-control body_font body_color', placeholder: "Station sequence"} %>
    </br>
    <%= f.submit "Submit".html_safe, :class => 'btn btn-lg btn-success body_font body_color' %>
<% end %>
</div>
</div>

bart_upstream/app/views/bartroutestations/_index_form.html.erb
<div class="col-lg-10 col-lg-offset-1">
<table class="table table-responsive table-bordered table-hover">
<tr>
    <th class="col-lg-1 body_font heading_color">Route</th>
    <th class="col-lg-1 body_font heading_color">Station</th>
    <th class="col-lg-1 body_font heading_color">Sequence No.</th>
    <th class="col-lg-1 body_font heading_color">DB Id</th>
  </tr>
	<% @bartroutestations.each do |bartroutestation| %>
		<tr>
			<% this_bartroute = Bartroute.find(bartroutestation.bartroute_id) %>
			<% this_bartstation = Bartstation.find(bartroutestation.bartstation_id) %>
			<td class="col-lg-1 body_font body_color"><%= this_bartroute.bart_route_name %></td>
			<td class="col-lg-1 body_font body_color"><%= this_bartstation.station_name %></td>
 			<td class="col-lg-1 body_font body_color"><%= bartroutestation.route_station_sequence %></td>
 			<td class="col-lg-1 body_font body_color"><%= bartroutestation.id %></td>
 			<td class="col-lg-1 body_font body_color"><%= link_to "Edit route stations", edit_bartroutestation_path(bartroutestation),
						:class => 'btn btn-info body_font' %></td>
		</tr>
	<% end %>
</table>

<%= link_to "Stations", bartstations_path,
						:class => 'btn btn-info body_font' %>

<%= link_to "Routes", bartroutes_path,
						:class => 'btn btn-info body_font' %>

<%= link_to "Create route stations", new_bartroutestation_path,
						:class => 'btn btn-info body_font' %>
</div>
</div>

bart_upstream/app/views/bartroutestations/edit.html.erb
<div class="col-lg-6 col-lg-offset-3">
<div class="well">
<table class="table table-responsive table-bordered table-hover">
<h1 class="col-lg-8 body_font col-lg-offset-3 heading_color">Edit Route Station</h1>

<%= render 'editform' %>

</div>
</div>

bart_upstream/app/views/bartroutestations/index.html.erb
<div class="col-lg-7 col-lg-offset-3">
<div class="well">
<table class="table table-responsive table-bordered table-hover">
<h1 class="col-lg-7 body_font col-lg-offset-2 heading_color">BART Route Stations</h1>

<%= render 'index_form' %>

</div>
</div>

bart_upstream/app/views/bartroutestations/new.html.erb
<div class="col-lg-6 col-lg-offset-3">
<div class="well">
<table class="table table-responsive table-bordered table-hover">
<h1 class="col-lg-8 body_font col-lg-offset-2 heading_color">Create A New Route Station</h1>

<%= render 'form' %>

</div>
</div>