bart_upstream/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  devise_for :users
  resources :bartstations

  resources :bartroutes

  resources :bartroutestations

  resources :bartjourneys
  
  get '/seed_stations' => 'bartstations#seed_bart_stations'

  get '/unseed_stations' => 'bartstations#unseed_bart_stations'

  get '/seed_bart_routes' => 'bartroutes#seed_bart_routes'

  get '/unseed_bart_routes' => 'bartroutes#unseed_bart_routes'

  get '/remove_bart_route_stations' => 'bartroutestations#remove_bart_route_stations'

  get '/sms' => 'bartjourneys#sms'

  get '/testme' => 'bartjourneys#testme'

  root 'bartjourneys#new'

end

bart_upstream/app/models/bartstation.rb
class Bartstation < ActiveRecord::Base

	has_many :bartroutestation

    validates :station_name, :presence => true
    validates :short_name, :presence => true
    validates :gtfs_latitude, :presence => true
    validates :gtfs_longitude, :presence => true
    validates :address, :presence => true
    validates :string, :presence => true
    validates :city, :presence => true
    validates :county, :presence => true
    validates :state, :presence => true
    validates :zipcode, :presence => true
 
end

bart_upstream/app/controllers/bartstations_controller.rb
class BartstationsController < ApplicationController
	include BartstationsHelper

	def index
		@bartstations = Bartstation.all
	end

	def new
		@bartstation = Bartstation.new
	end

	def create
		# Create a new post using the params provided from 
		# the view and redirect back to the main index page
		@bartstation = Bartstation.new(station_params)
		if @bartstation.save
			flash[:success] = "Station created"
			redirect_to bartstations_path 
		else
			flash[:error] = "Unable to save station. Please try again"
			render :create
		end
	end

	def show
		@bartstations = Bartstation.all
	end

	def seed_bart_stations
		# Seed the database with the station details downloaded from the BART API
		load_bart_station_names
		redirect_to bartstations_path
	end

	def unseed_bart_stations
		# Remove all the stations from the database
		remove_bart_station_names
		redirect_to bartstations_path
	end

	def source
		# Check the direction of travel. N = normal direction, R = reverse
		if params["direction"] = "N"
			get_departure_times(params["start_station"],params["end_station"])
			binding.pry
		else
			binding.pry
		end
	end

	private

	def station_params
		params.require(:station_name, :short_name, :gtfs_latitude, :gtfs_longitude, 
			:address, :city, :county, :state, :zipcode).permit(:station_name, :short_name, 
			:gtfs_latitude, :gtfs_longitude, :address, :city, :county, :state, :zipcode)
	end


end

bart_upstream/app/helpers/bartstations_helper.rb
module BartstationsHelper
# Helper functions for Stations

	# Get all the station names from the BART API
	# This will be changing to retrieve the list from the database to 
	# reduce the number of API calls

	def get_station_names

		# Typhoeus is used to submit http requests

		  response = Typhoeus.get("http://api.bart.gov/api/stn.aspx?cmd=stns&key=ZZLI-UU93-IMPQ-DT35")

		  # Extract the station names and short names

		  response_XML = Nokogiri.XML(response.body)

		  @station_names = {}

		  # Create a hash list of the station names and abbreviations
		  # node provides the full name of the station and next node is 
		  # the abbreviation

		  response_XML.xpath("//stations/station/name").each do |node|
#		  		@station_names[node.text] = node.next.text
				@station_names[response_XML.at_css('name').content] = 
					response_XML.at_css('abbr').content
		  		
		  end

		  return @station_names

	end

	# Get the trains departing from the selected departure station and 
	# determine which one goes to the selected destination.
	# For the first phase any train transfers will not be supported

	def get_departure_times(departure_station,destination_station)

		# Typhoeus is used to submit http requests

		  bart_url = "http://api.bart.gov/api/etd.aspx?cmd=etd&orig=#{departure_station}&key=ZZLI-UU93-IMPQ-DT35"

		  response = Typhoeus.get(bart_url)

		  # Extract the departure times to the chosen destination

		  response_XML = Nokogiri.XML(response.body)

		  @departure_times = {}

		  # Create a hash list of the departure times

		  response_XML.xpath("//station/etd/destination").each do |node|
		  		@departure_times[node.text] = node.next.text
		  		binding.pry
		  end

		  binding.pry

		  return @departure_times

	end

	# One-time population of the database with the station names from the BART API

	def load_bart_station_names

		# Typhoeus is used to submit http requests

		response = Typhoeus.get("http://api.bart.gov/api/stn.aspx?cmd=stns&key=ZZLI-UU93-IMPQ-DT35")

		# Extract the station names and short names and store them in the database

		response_XML = Nokogiri.XML(response.body)

		@station_names = {}

		response_XML.xpath("//stations/station").each do |node|
		  	@station = Bartstation.new
			@station.station_name = (node/'./name').text
			@station.short_name = (node/'./abbr').text
			@station.gtfs_latitude = (node/'./gtfs_latitude').text
  			@station.gtfs_longitude = (node/'./gtfs_longitude').text
  			@station.address = (node/'./address').text
  			@station.city = (node/'./city').text
  			@station.county = (node/'./county').text
  			@station.state = (node/'./state').text
  			@station.zipcode = (node/'./zipcode').text
			if @station.save
				flash[:success] = "Station #{@station.station_name} created" 
			else
				flash[:error] = "Unable to save station #{@station.station_name}. Please try again"
			end
		end
	end

	# Remove all the station information from the database. Used in testing only
	def remove_bart_station_names
		@stations = Bartstation.all
		@stations.each do |station|
			station.destroy
		end
	end
end

bart_upstream/app/views/bartstations/_index_form.html.erb
<div class="col-lg-7 col-lg-offset-2">
<div class="well">

<p class="body_font body_color">
Please choose a start and destination station:
</p>
<%= simple_form_for(@bartstations, 
    html: {:class => 'form-horizontal'}) do |f| %>
    <% binding.pry %>
    <%= f.input :start_station_id, collection: @start_stations, label: false, 
        input_html:{:class => 'form-control body_font body_color'} %>
    </br>
    <%= f.input :end_station_id, collection: @end_stations,label: false, 
        input_html:{:class => 'form-control body_font body_color'} %>
    </br>
    <%= f.submit "Submit".html_safe, :class => 'btn btn-lg btn-success body_font body_color' %>
<% end %>
</div>
</div>

bart_upstream/app/views/bartstations/get_journey.html.erb
<div class="col-lg-10 col-lg-offset-1">
<div class="well">
<table class="table table-responsive table-bordered table-hover">
<h1 class="col-lg-4 body_font col-lg-offset-4 heading_color">Journey Details</h1>

<div class="col-lg-7 col-lg-offset-2">
<div class="well">

<p class="body_font body_color">
Please choose a start and destination station:
</p>
<%= simple_form_for(@bartstations, 
    html: {:class => 'form-horizontal'}) do |f| %>
    <% binding.pry %>
    <%= f.input :start_station_id, collection: @bartstations, label: false, 
        input_html:{:class => 'form-control body_font body_color'} %>
    </br>
    <%= f.input :end_station_id, collection: @bartstations,label: false, 
        input_html:{:class => 'form-control body_font body_color'} %>
    </br>
    <%= f.submit "Submit".html_safe, :class => 'btn btn-lg btn-success body_font body_color' %>
<% end %>
</div>
</div>
</table>
</div>
</div>

bart_upstream/app/views/bartstations/index.html.erb
<div class="col-lg-10 col-lg-offset-1">
<div class="well">
<table class="table table-responsive table-bordered table-hover">
<h1 class="col-lg-4 body_font col-lg-offset-4 heading_color">Station Details</h1>
  <tr>
    <th class="col-lg-1 body_font heading_color">Station</th>
    <th class="col-lg-1 body_font heading_color">Abbreviation</th>
    <th class="col-lg-1 body_font heading_color">Latitude</th>
    <th class="col-lg-1 body_font heading_color">Longitude</th>
    <th class="col-lg-1 body_font heading_color">Address</th>
    <th class="col-lg-1 body_font heading_color">City</th>
    <th class="col-lg-1 body_font heading_color">County</th>
    <th class="col-lg-1 body_font heading_color">State</th>
    <th class="col-lg-1 body_font heading_color">Zip</th>
    <th class="col-lg-1 body_font heading_color">DB Id</th>
  </tr>
	<% @bartstations.each do |station| %>
		<tr>
			<td class="col-lg-1 body_font body_color"><%= station.station_name %></td>
			<td class="col-lg-1 body_font body_color"><%= station.short_name %></td>
 			<td class="col-lg-1 body_font body_color"><%= station.gtfs_latitude %></td>
			<td class="col-lg-1 body_font body_color"><%= station.gtfs_longitude %></td>
			<td class="col-lg-1 body_font body_color"><%= station.address %></td>
			<td class="col-lg-1 body_font body_color"><%= station.city %></td>
			<td class="col-lg-1 body_font body_color"><%= station.county %></td>
			<td class="col-lg-1 body_font body_color"><%= station.state %></td>
			<td class="col-lg-1 body_font body_color"><%= station.zipcode %></td>
			<td class="col-lg-1 body_font body_color"><%= station.id %></td>
		</tr>
	<% end %>
</table>

<%= link_to "Create stations", bartstations_path,
						:class => 'btn btn-info body_font' %>

<%= link_to "View routes", bartroutes_path,
						:class => 'btn btn-info body_font' %>


<%= link_to "View route stations", bartroutestations_path,
						:class => 'btn btn-info body_font' %>

<%= link_to "Seed stations", seed_stations_path,
						:class => 'btn btn-info body_font' %>

<%= link_to "Unseed stations", unseed_stations_path,
						:class => 'btn btn-info body_font' %>

</div>
</div>

bart_upstream/app/views/bartstations/show.html.erb
<div class="col-lg-10 col-lg-offset-1">
<div class="well">
<table class="table table-responsive table-bordered table-hover">
<h1 class="col-lg-4 body_font col-lg-offset-4 heading_color">Station Details</h1>
  <tr>
    <th class="col-lg-1 body_font heading_color">Station</th>
    <th class="col-lg-1 body_font heading_color">Abbreviation</th>
    <th class="col-lg-1 body_font heading_color">Latitude</th>
    <th class="col-lg-1 body_font heading_color">Longitude</th>
    <th class="col-lg-1 body_font heading_color">Address</th>
    <th class="col-lg-1 body_font heading_color">City</th>
    <th class="col-lg-1 body_font heading_color">County</th>
    <th class="col-lg-1 body_font heading_color">State</th>
    <th class="col-lg-1 body_font heading_color">Zip</th>
  </tr>
	<% @bartstations.each do |station| %>
		<tr>
			<td class="col-lg-1 body_font body_color"><%= station.station_name %></td>
			<td class="col-lg-1 body_font body_color"><%= station.short_name %></td>
 			<td class="col-lg-1 body_font body_color"><%= station.gtfs_latitude %></td>
			<td class="col-lg-1 body_font body_color"><%= station.gtfs_longitude %></td>
			<td class="col-lg-1 body_font body_color"><%= station.address %></td>
			<td class="col-lg-1 body_font body_color"><%= station.city %></td>
			<td class="col-lg-1 body_font body_color"><%= station.county %></td>
			<td class="col-lg-1 body_font body_color"><%= station.state %></td>
			<td class="col-lg-1 body_font body_color"><%= station.zipcode %></td>
		</tr>
	<% end %>
</table>

<%= link_to "Create stations", bartstations_path,
						:class => 'btn btn-info body_font' %>

<%= link_to "View routes", bartroutes_path,
						:class => 'btn btn-info body_font' %>


<%= link_to "View route stations", bartroutestations_path,
						:class => 'btn btn-info body_font' %>

<%= link_to "Seed stations", seed_stations_path,
						:class => 'btn btn-info body_font' %>

<%= link_to "Unseed stations", unseed_stations_path,
						:class => 'btn btn-info body_font' %>

</div>
</div>