bart_upstream/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  devise_for :users
  resources :bartstations

  resources :bartroutes

  resources :bartroutestations

  resources :bartjourneys
  
  get '/seed_stations' => 'bartstations#seed_bart_stations'

  get '/unseed_stations' => 'bartstations#unseed_bart_stations'

  get '/seed_bart_routes' => 'bartroutes#seed_bart_routes'

  get '/unseed_bart_routes' => 'bartroutes#unseed_bart_routes'

  get '/remove_bart_route_stations' => 'bartroutestations#remove_bart_route_stations'

  get '/sms' => 'bartjourneys#sms'

  get '/testme' => 'bartjourneys#testme'

  root 'bartjourneys#new'

end

bart_upstream/app/models/bartroute.rb
class Bartroute < ActiveRecord::Base
	has_many :bartroutestation
	validates :bart_route_name, :presence => true
	validates :bart_route_name, :presence => true
	validates :bart_route_short_name, :presence => true
    validates :bart_route_id, :presence => true
    validates :bart_route_number, :presence => true
    validates :bart_route_color, :presence => true
end

bart_upstream/app/controllers/bartroutes_controller.rb
class BartroutesController < ApplicationController
	include BartroutesHelper

	def index
		@bartroutes = Bartroute.all.order(:bart_route_id)
	end

	def new
		@bartroute = Bartroute.new
	end

	# Create a new route using the params provided from 
	# the view and redirect back to the main index page
	def create
		@bartroute = Bartroute.new(bartroute_params)
		if @bartroute.save
			flash[:success] = "Route created"
			redirect_to bartroutes_path 
		else
			flash[:error] = "Unable to save route. Please try again"
			render :create
		end
	end

	def seed_bart_routes
		load_bart_routes
		redirect_to bartroutes_path
	end

	def unseed_bart_routes
		remove_bart_routes
		redirect_to bartroutes_path
	end

	private

	def bartroute_params
		params.require(:bart_route_name, :bart_route_color, :bart_route_short_name, :bart_route_id, 
			:bart_route_number).permit(:bart_route_name, :bart_route_color, :bart_route_short_name, :bart_route_id, 
			:bart_route_number)
	end
end

bart_upstream/app/helpers/bartroutes_helper.rb
module BartroutesHelper

# Helper functions for Routes

	# One-time population of the database with the routes from the BART API

	def load_bart_routes

		response = Typhoeus.get("http://api.bart.gov/api/route.aspx?cmd=routes&key=ZZLI-UU93-IMPQ-DT35")

		# Extract the route details and store them in the database

		response_XML = Nokogiri.XML(response.body)

		@bartroutes = {}

		response_XML.xpath("//routes/route").each do |node|
		  	@bartroute = Bartroute.new
			@bartroute.bart_route_name = (node/'./name').text
			@bartroute.bart_route_short_name = (node/'./abbr').text
			@bartroute.bart_route_id = (node/'./routeID').text
  			@bartroute.bart_route_number = (node/'./number').text
  			@bartroute.bart_route_color = (node/'./color').text
 			if @bartroute.save
				flash[:success] = "Route #{@bartroute.bart_route_name} created" 
			else
				flash[:error] = "Unable to save route #{@bartroute.bart_route_name}. Please try again"
			end
		end
	end

	# Remove all the station information from the database. Used in testing only
	def remove_bart_routes
		@bartroutes = Bartroute.all
		@bartroutes.each do |bartroute|
			bartroute.destroy
		end
	end

end

bart_upstream/app/views/bartroutes/index.html.erb
<div class="col-lg-10 col-lg-offset-1">
<div class="well">
<table class="table table-responsive table-bordered table-hover">
<h1 class="col-lg-4 body_font col-lg-offset-4 heading_color">Route Details</h1>
  <tr>
    <th class="col-lg-1 body_font heading_color">Route</th>
    <th class="col-lg-1 body_font heading_color">Abbreviation</th>
    <th class="col-lg-1 body_font heading_color">Route ID</th>
    <th class="col-lg-1 body_font heading_color">Route No.</th>
    <th class="col-lg-1 body_font heading_color">Route Color</th>
    <th class="col-lg-1 body_font heading_color">DB Id</th>
  </tr>
	<% @bartroutes.each do |bartroute| %>
		<tr>
			<td class="col-lg-1 body_font body_color"><%= bartroute.bart_route_name %></td>
			<td class="col-lg-1 body_font body_color"><%= bartroute.bart_route_short_name %></td>
 			<td class="col-lg-1 body_font body_color"><%= bartroute.bart_route_id %></td>
			<td class="col-lg-1 body_font body_color"><%= bartroute.bart_route_number %></td>
			<td class="col-lg-1 body_font body_color"><%= bartroute.bart_route_color %></td>
			<td class="col-lg-1 body_font body_color"><%= bartroute.id %></td>
		</tr>
	<% end %>
</table>

<%= link_to "Stations", bartstations_path,
						:class => 'btn btn-info body_font' %>

<%= link_to "Create routes", bartroutes_path,
						:class => 'btn btn-info body_font' %>

<%= link_to "View route stations", bartroutestations_path,
						:class => 'btn btn-info body_font' %>

<%= link_to "Edit route stations", edit_bartroutestation_path(19),
						:class => 'btn btn-info body_font' %>

<%= link_to "Seed routes", seed_bart_routes_path,
						:class => 'btn btn-info body_font' %>

<%= link_to "Unseed routes", unseed_bart_routes_path,
						:class => 'btn btn-info body_font' %>

</div>
</div>